### ISSUE TITLE
Canvas events (preventDefault)

### ISSUE THREAD

**Issue by BananaRush** [excubo-ag/Blazor.Canvas#132]
Hello! this code doesn't work

`
<Canvas 
        @onwheel="WheelEvent"
        @onwheel:preventDefault/>
`

_Error: The component parameter 'onwheel' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'onwheel' is generated by the '@onwheel:preventDefault' directive attribute.	BlazorApp.Client_

I want to use "preventDefault" for the Canvas element according to the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1)

Thanks!

**Comment by stefanloerwald** [comment]
Hi @BananaRush,

this seems to be a general issue in Blazor: unless those events are explicitly implemented by the component, those events will not work. I filed a bug here: https://github.com/dotnet/aspnetcore/issues/25647

Regarding the use with `Excubo.Blazor.Canvas`, I recommend writing the following: 
```
@inject Microsoft.JSInterop.IJSRuntime js;
<canvas @ref="normal_canvas" width="600" height="300" @onwheel="WheelEvent" @onwheel:preventDefault></canvas>

@code {
    private ElementReference normal_canvas;
    private async Task DrawAsync()
    {
        await using (var ctx = await js.GetContext2DAsync(normal_canvas))
        {
            //...
        }
    }
}
```
