### ISSUE TITLE
DrawingImages

### ISSUE THREAD

**Issue by joseluisbejarfernandez** [excubo-ag/Blazor.Canvas#133]
Hello Stefan,

Please, could you give an examplo of using this:

https://excubo-ag.github.io/Blazor.Canvas/2D/DrawingImages

I am trying to use it and i do not kwno how to use the input parameter "string image".

B.R.

**Comment by stefanloerwald** [comment]
Hi @joseluisbejarfernandez,

the parameter refers to any variable in JS that holds a reference to an image. For example, this can be an image that you reference from the DOM (see https://github.com/excubo-ag/Blazor.Canvas/blob/main/TestProject_Components/Context2D/DrawingImages.razor) or my constructing it inline. Creating the correct image source is responsibility of the user (there are way too many ways to do it, so the library can't take care of it).

I have added the documentation for this API and you can play with the demo here: https://excubo-ag.github.io/Blazor.Canvas/2D/DrawingImages

**Comment by joseluisbejarfernandez** [comment]
Hello Stefan,

Thank you so much for your fast reply!.

Please, could you gime me also the javascript code of this:

await js.InvokeVoidAsync("eval", "myimage = document.getElementById('blazor_logo')");

Could you give me the javascript function called "eval"?

Thanks in advance!

**Comment by stefanloerwald** [comment]
`eval` is a javascript built-in. It is already available to you in Blazor without any library.

**Comment by joseluisbejarfernandez** [comment]
Solved!

Thank you! ;-)
