### ISSUE TITLE
canvas.toDataURL();

### ISSUE THREAD

**Issue by joseluisbejarfernandez** [excubo-ag/Blazor.Canvas#134]
Hello again Stefan,

Please could you say to me how to create a Base64 string with your canvas library like this javascript code?

https://developer.mozilla.org/es/docs/Web/API/HTMLCanvasElement/toDataURL

B.R.

**Comment by stefanloerwald** [comment]
`toDataURL` was not available so far, but now is. Upgrade to version 2.2.0 to get it. Demo is available here: https://excubo-ag.github.io/Blazor.Canvas/dataURL

**Comment by joseluisbejarfernandez** [comment]
Please Stefan, coud you give me a code example of this new feature?

**Comment by stefanloerwald** [comment]
For all demo pages, there's a link to source code in the top right corner of the page:

![image](https://user-images.githubusercontent.com/10850250/93062853-c2524700-f675-11ea-9ea3-80dc9ac9544c.png)

In this case, that will lead you to https://github.com/excubo-ag/Blazor.Canvas/blob/main/TestProject_Components/Pages/DataURL.razor and you'll find the call to `ToDataURLAsync` in line 32: https://github.com/excubo-ag/Blazor.Canvas/blob/40dff5c00c5ad675db8509d9fe3f4e3964099554/TestProject_Components/Pages/DataURL.razor#L32

**Comment by joseluisbejarfernandez** [comment]
Ok, thank you so much! 😁
