### ISSUE TITLE
DrawImageAsync

### ISSUE THREAD

**Issue by EaglesFlight** [excubo-ag/Blazor.Canvas#144]
When I draw an image in the OnAfterRenderAsync, the image won't show first time. Only after leaving the page and coming back, it shows.

If I draw the image in an event such click event of a button or check event of a checkbox it works.

Do you know how to have the image shown as soon as the page loads by drawing it in the OnAfterRenderAsync  event?

       <img id="board" width="553" height="598" style="display:none" src="images/main_canvas.png" />
       <canvas id="canvas" @ref="canvasBoard" width="553" height="598" />

.
.
.

        protected override async Task OnAfterRenderAsync(bool first_render)
        {
            if (first_render)
            {
                await js.InvokeVoidAsync("eval", "boardimage = document.getElementById('board')");
                await using (var canvas = await js.GetContext2DAsync(canvasBoard))
                {
                      await canvas.ClearRectAsync(0, 0, 553, 598);
                      await canvas.DrawImageAsync("boardimage", 0, 0);
                      await InvokeAsync(StateHasChanged);
                }         
            }   
        }

Thanks!
Carlos

**Comment by stefanloerwald** [comment]
Hi @EaglesFlight,

The interactions with the canvas API happen independently from blazor rendering. So the call to StateHasChanged is not necessary. What you are probably experiencing is a re-render of the component, which for some reason resets the canvas element. If it's reset, but the drawing code isn't executed again, you see a blank canvas, even though it was correctly drawn on the first time. 

BR 
Stefan

**Comment by EaglesFlight** [comment]
Hi Stefan,

This code executes only once in the prerender event because of the (if first_render).

The problem persists even without the StateHasChanged. It looks to me the JS code to load the image is somehow out of sync and the canvas don't find the image to drawing.

When I use similar code in JavaScript without Blazor, I have to rely on JQuery to make sure the image is loaded before the canvas can draw the image.


$(img).load(function(){
   canvas.drawImage(img,0,0);
 });

But I don't know how to enforce it in Blazor if this is ever possible.

Thanks,
Carlos

**Comment by stefanloerwald** [comment]
Hi Carlos,

neither blazor nor this library will make your image load instantly, so it is your responsibility to only draw to the canvas after the image is loaded. Why don't you add `@onload="InitializeCanvas"` to your img element? 

Stefan

**Comment by EaglesFlight** [comment]
Hi Stefan,

Still no luck.  If you ever try it, please let me know. Thank you!

<img id="board" @onload="DrawCanvas" style="display:none" src="images/Bmain_canvas.png" />
<canvas id="canvas" @ref="canvasBoard" />

.
.
.
 private ElementReference canvasBoard;
.
.
.
        private async Task DrawCanvas()
        {            
            await using (var canvas = await js.GetContext2DAsync(canvasBoard))
            {
                await js.InvokeVoidAsync("eval", "boardimage = document.getElementById('board')");
                await canvas.DrawImageAsync("boardimage", 0, 0);
            }            
        }

**Comment by stefanloerwald** [comment]
I have tried it. It's in the examples of this repo: here's the [demo](https://excubo-ag.github.io/Blazor.Canvas/2D/DrawingImages) and its [code](https://github.com/excubo-ag/Blazor.Canvas/blob/main/TestProject_Components/Pages/Context2D/DrawingImages.razor).

This [documentation on onload](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload) says it should fire when the image is loaded. Did you try hooking into this?

**Comment by EaglesFlight** [comment]
Hi Stefan,

I saw the demo and code a long ago. As I said, it works for me too if the image is drawn as a result of a check box or click button event. In you sample, the images are only drawn after you check the checkboxes.

The problem happens if you need to draw it when the page first loads. If can get it to work please let me know.

Thanks,
Carlos

**Comment by stefanloerwald** [comment]
Again, have you tried `onload`?

**Comment by EaglesFlight** [comment]
Yes, please see one of my comment above with the code.

The code runs, breakpoint stops at the line the canvas is supposed to be drawn but it doesn't work.

Thanks!
Carlos

**Comment by stefanloerwald** [comment]
Sorry, I haven't spotted that due to the broken code formatting in that message. Have you tried introducing a small delay before the canvas code?

**Comment by EaglesFlight** [comment]
I did. I tried also drawing the image twice, or three times.

If you leave the page and comes back, the image magically shows with exactly the same code on the pre-render. But it won't load the very first time the page loads.

For now I am going to have a checkbox on the page "Show Canvas". It's a bit annoying but from there everything is super fine with the Blazor Canvas.

Many thanks for your work and willing to help!
Carlos

**Comment by stefanloerwald** [comment]
Hi Carlos,

I just created a small example page and on server-side blazor it works just fine. However, I can confirm the issue on blazor wasm. I'll try and see what the issue might be here.

BR
Stefan

**Comment by stefanloerwald** [comment]
The issue is relatively straight-forward, when combining all the info about the involved technologies:

- Images don't load instantly. We have to wait until the image is loaded, before we can use its content to draw on the canvas
- We have to use `onload` to get informed of the completion
- `onload` has to be applied to the `img` element _before_ `src`. This is where blazor fails.
- Blazor treats event callbacks differently to other attributes, so the `@onload` will be "too late": the image loading has already started, but you won't get a notification.
- On subsequent page visits, the url is already cached, so naturally it loads fast enough now

We have to work around that, sadly. A quick test shows that the following works:

```js
        window.loadImage = (ref, id, url) => {
            const img = document.getElementById(id);
            img.onload = () => ref.invokeMethodAsync('UpdateCanvasAsync');
            img.src = url;
        }
```

```cs
<hr />
<img id="castle" width="3840" height="2160" style="display:none" />

<hr />
<Canvas @ref="canvas" width="384px" height="216px" style="border: 5px solid red" />

@inject IJSRuntime js
@code {
    private Canvas canvas;
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await js.InvokeVoidAsync("loadImage", DotNetObjectReference.Create(this), "castle", "https://upload.wikimedia.org/wikipedia/commons/4/45/Nagoya_Castle%28Larger%29.jpg");
        }
        await base.OnAfterRenderAsync(firstRender);
    }
    [JSInvokable]
    public async Task UpdateCanvasAsync()
    {
        await js.InvokeVoidAsync("eval", "myimage = document.getElementById('castle')");
        await using (var ctx = await canvas.GetContext2DAsync())
        {
            await ctx.ClearRectAsync(0, 0, 384, 216);
            await ctx.DrawImageAsync("myimage", 0, 0, 3840, 2160, 0, 0, 384, 216);
        }
    }
}
```

(the DotNetObjectReference should be disposed on disposal of that component. I've omitted that from this sample code).

**Comment by stefanloerwald** [comment]
The sample page is hidden from the demo page, as it constitutes a very narrow edge case. However, you can find it with the direct link: https://excubo-ag.github.io/Blazor.Canvas/2D/DrawingImageImmediately

**Comment by EaglesFlight** [comment]
Hi Stefan,

This worked perfectly fine. Thanks a lot for your help and explanation!

Cheers!
Carlos
