### ISSUE TITLE
Exception with MeasureTextAsync

### ISSUE THREAD

**Issue by PascalFarled** [excubo-ag/Blazor.Canvas#149]
Hello ,

i found a problem when trying to use the method MeasureTextAsync with string arg that contains single quote into it
exemple : with this string arg : "L'ouverture du magasin"

it seems that the problem is related to escape chars in javascript (JS interop).
with the sample string arg i have this output exception in browser console : 

![image](https://user-images.githubusercontent.com/36106252/122634799-c61d6900-d0e0-11eb-92de-9d7dc8113f30.png)

Do you have any ideas how to fix that ?

Many thx,

Regard,  Valentin

**Comment by stefanloerwald** [comment]
Hi @PascalFarled,

thanks for raising this issue. It is indeed a bug, which I just fixed in version 2.6.5. 

BR
Stefan
