### ISSUE TITLE
ClipAsync not working when in a batch

### ISSUE THREAD

**Issue by bmcdonaldv** [excubo-ag/Blazor.Canvas#151]
I was cleaning up some code and it seems that ClipAsync doesn't work in a Batch2D.  It works when called from Context2D.

**Comment by bmcdonaldv** [comment]
[here](https://github.com/excubo-ag/Blazor.Canvas/blob/28f810c1c2c669cd9029c0b165d70d3904cfcd00/Canvas/Contexts/Context2D_DrawingPaths.cs#L192
)

Should that be invoke?

**Comment by stefanloerwald** [comment]
Hi @bmcdonaldv,

You're 100% right. This is the same problem as #148, but for batching, which I missed when fixing #148. I'm in the process of creating a new version (2.6.6), so this should be resolved with the next update.

Thanks for raising this issue!

Best regards
Stefan

**Comment by bmcdonaldv** [comment]
@stefanloerwald yes it works great.  Thanks for looking at it.
