### ISSUE TITLE
Demo link does not load

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [excubo-ag/Blazor.Canvas#152]
**Steps to reproduce:**
* click on [Demo](https://excubo-ag.github.io/Blazor.Canvas/) link

**Observed:**
* page has:
  * `Loading` text
  * `An unhandled error has occurred. Reload`
* errors in Google Chrome console:
```bash
Failed to find a valid digest in the 'integrity' attribute for resource 'https://excubo-ag.github.io/Blazor.Canvas/_framework/TestProject_ClientSide.dll' with computed SHA-256 integrity '94Sr2R0Ne5tEy7lcHJOOMHcdEwvXzFKXhpEXVXW4iW4='. The resource has been blocked.
excubo-ag.github.io/:1 Unknown error occurred while trying to verify integrity.
excubo-ag.github.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://excubo-ag.github.io/Blazor.Canvas/_framework/System.Collections.Concurrent.dll' with computed SHA-256 integrity 'bRXqW6Ih7fwtfPX2uP9TMWVV+Au+Bpu2L0nLwGBxS/o='. The resource has been blocked.
excubo-ag.github.io/:1 Unknown error occurred while trying to verify integrity.
```
etc

**Expected:**
* demo to load without error

**Configuration:**
* Google Chrome
* Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by stefanloerwald** [comment]
Thanks for reporting this. I can't quite see the reason for it, as the build process is identical to other demo sites in the same org, which seem to work. I've just triggered a re-run of the last action workflow to see whether that does anything.

**Comment by stefanloerwald** [comment]
Please try again now. You may need to force a reload / empty the browser cache. It works again for me

**Comment by TrevorDArcyEvans** [comment]
Working now.  Thanks for the prompt response.
