### ISSUE TITLE
Touch not Support on Whiteboard

### ISSUE THREAD

**Issue by schorges** [excubo-ag/Blazor.Canvas#154]
Is there something planned for mobile / touch support.

I want to paint on the whiteboard with pen in a blazor app,
At the moment i'm injecting canvas with java like this:
[https://zipso.net/a-simple-touchscreen-sketchpad-using-javascript-and-html5/](url)

**Comment by stefanloerwald** [comment]
Hi @schorges,

This project is exclusively about the canvas API. That means you can draw on a canvas however you please, or interact with it any way you want to. What this project doesn't do is provide any methods that handle touch/clicks. That's essentially up to you. As you can see on our [demo page](https://excubo-ag.github.io/Blazor.Canvas), a [whiteboard](https://excubo-ag.github.io/Blazor.Canvas/2D/whiteboard) is certainly feasible. The example uses mouse events, but they can very easily be replaced/amended by the touch events.

BR
Stefan
