### ISSUE TITLE
Stacking

### ISSUE THREAD

**Issue by bearsystems** [excubo-ag/Blazor.Canvas#156]
This might not be considered an issue, however I am attempting to layer a canvas underneath a div tag that contains a large number of custom objects.  The intent is to draw lines between those objects on the canvas and thus make the objects look as if they are connected.  I have tried using z-index both in CSS and directly in the style tag on the canvas element and it is not working, The canvas simply pushing the content down the page.   Is this by design or is there a setting that I am missing?  Thank you!

**Comment by stefanloerwald** [comment]
Hi @bearsystems,

This is in fact not an issue of this library ;-)

z-index alone will _not_ help you place things on top of each other. What you need is `position` as well.
Here's a demo of that (not my site, I just found that after a quick search): https://www.tutorialrepublic.com/codelab.php?topic=faq&file=css-overlay-one-div-over-another-div

Hope that helps!
Stefan
