### ISSUE TITLE
Image Smoothing Enabled set not working

### ISSUE THREAD

**Issue by Magehernan** [excubo-ag/Blazor.Canvas#161]
Hi, i am drawing like pixel art imagen in the canvas and i need to disable smoothing, 
The problem is that the method  from Context

protected ValueTask SetAsync(string field, bool value) => SetAsync(field, value.ToString());

when you pass a bool it convert it to string, instead of put the value directly. So i change it to

protected ValueTask SetAsync(string field, bool value) => InvokeEvalAsync(field, value.ToString().ToLowerInvariant());

and now it is working...

I will make a pull request.

**Comment by stefanloerwald** [comment]
Thank you for investigating and providing a bug fix PR. The release is in progress.

**Comment by Magehernan** [comment]
thank you for sharing this!
