### ISSUE TITLE
DrawImage with using map to provide image not working in batch

### ISSUE THREAD

**Issue by Magehernan** [excubo-ag/Blazor.Canvas#163]
Hi, i encounter this problem, i am loading images in background and storing them in a map on javascript side, then i use on c# 

await batch.DrawImageAsync($"imagesMap.get(\"{name}\")", 0, 0, chunkWidth, chunkHeight, imageX, imageY, imageWidth, imageHeight);

and it throw an error telling me that the type is not supported.

if i call the same way in the context, it works, so i am really new on using canvas and batching so maybe is not really important using it and only using the context is fine.

I look at the code but i don't really undestand why it is not calling the same way that is called on the context.

best regards

**Comment by stefanloerwald** [comment]
Hi @Magehernan,

You're right that this doesn't behave in the same way. `$"imagesMap.get("{name}")"` as argument to `DrawImageAsync` was never intended to work, neither in batch nor non-batch mode. It just happens to work in non-batch mode. The argument must be a named image, so somewhere else you need to perform `some_image_name = imagesMap.get("key");` and then you'll be able to use `await batch.DrawImageAsync("some_image_name", 0, 0, chunkWidth, chunkHeight, imageX, imageY, imageWidth, imageHeight);` in both batch and non-batch.

Hope that helps
Stefan
