### ISSUE TITLE
draw RGBA byte array to canvas

### ISSUE THREAD

**Issue by Hackmodford** [excubo-ag/Blazor.Canvas#164]
Is there a way I could draw an RGBA byte array to the canvas using this library?

**Comment by stefanloerwald** [comment]
Hi @Hackmodford,

I don't recall seeing this option in the canvas API and this library doesn't add much fancy things on top. I'd imagine that there's an Image API to create images from byte arrays, which you could wrap to create images, then pass them on to this library. Creating Images or any other JS objects is out of scope for this library.

Hope that helps
Stefan

**Comment by Hackmodford** [comment]
It seems that I should be able to use putImageData and modify the byte array of an imageData object. But that happens on the JS side of things.

**Comment by stefanloerwald** [comment]
Hi @Hackmodford,

It's still not quite clear to me what the ask is here. Could you please show code?

Thanks
Stefan

**Comment by gmkado** [comment]
Hi @stefanloerwald I'd also be interested in this feature.  I think what @Hackmodford is referring to is documented here:
https://developer.mozilla.org/en-US/docs/Web/API/ImageData/data#examples

**Comment by stefanloerwald** [comment]
The skeleton of this is implemented, see https://github.com/excubo-ag/Blazor.Canvas/blob/main/Canvas%2FContexts%2FContext2D_PixelManipulation.cs#L50.
However, setting any of the imagedata pixels is not supported here. The design of this library is based on individual or batched calls to the JS Api. Setting thousands of pixels individually would likely result in very bad performance and is for that reason not planned.
