### ISSUE TITLE
Canvas component paramaters  stopPropagation or preventDefault throws error

### ISSUE THREAD

**Issue by juancarloshb5** [excubo-ag/Blazor.Canvas#165]
When trying to use the stopPropagation or preventDefault throws an error

<Canvas 
        @oncontextmenu="OnContextMenu"
        @oncontextmenu:stopPropagation="true"
        @oncontextmenu:preventDefault="true"
    />

Error Message: "The component parameter 'oncontextmenu' is used two or more times

Thanks for share , been testing this library and its great!

**Comment by stefanloerwald** [comment]
Hi @juancarloshb5,

This is a longstanding limitation of components and there's nothing we can do about it. I recommend switching to a native canvas element (see the Readme on how using the component vs element differ), because the limitation doesn't apply to elements.

Hope that helps,
Stefan
