### ISSUE TITLE
Question: How to resize a canvas to fit the screen?

### ISSUE THREAD

**Issue by iSeiryu** [excubo-ag/Blazor.Canvas#166]
Is there an easy way to dynamically resize a canvas so it would scale with the window's size change? 
Browsers can be opened on many different screens and sized differently too. There are 2 parts to this question:
1. How to capture the initial window size to set the initial canvas's size?
2. How to resize the canvas together with the window?

**Comment by stefanloerwald** [comment]
It sounds like you're trying to do something akin to this: https://stackoverflow.com/a/8486324/985296

Resizing the canvas element is outside of the scope of this library, as it's not part of the canvas API.

**Comment by iSeiryu** [comment]
>Resizing the canvas element is outside of the scope of this library
I know, hence it was just a question. People that work with Blazor and canvases may run into the same need and might have a solution already that they could share.
