### ISSUE TITLE
Can not build solution after cloning

### ISSUE THREAD

**Issue by Kahdeg-15520487** [excubo-ag/Blazor.Canvas#168]
Hi, i just clone the repository, open the solution in visual studio (17.4.3) and build the solution.
here are the errors:
![image](https://user-images.githubusercontent.com/15503419/224892514-9e474384-eb34-45cb-8811-c50083d7254a.png)

**Comment by stefanloerwald** [comment]
This is most likely an incompatibility regarding the dotnet SDK. Try updating it. If that doesn't help or no update is available, just undo the latest git commit(s).

Hope that helps
Stefan

**Comment by Kahdeg-15520487** [comment]
i updated vs to 17.5.1 and can build the repository normally now.
