### ISSUE TITLE
Project is missing 'Group' from Excubo.Generators.Grouping

### ISSUE THREAD

**Issue by ingmarcrone** [excubo-ag/Blazor.Canvas#169]
Hi,

Project is missing 'Group' from Excubo.Generators.Grouping

tried to fix it with:
- rebuild
- re install package
- download package project from git 

Just didn't succeed.

a downgrade to Excubo.Generators.Grouping 1.4.15 WORKS though!

With kind regards,
Ingmar Crone

**Comment by stefanloerwald** [comment]
The most likely cause is an outdated SDK. Could you check that please?

**Comment by ingmarcrone** [comment]
It depends on what you mean.
The SDK is indeed older, but it's the  main branch of the repository.
The blazor version used in the sdk is also older.

Since the sdk works if the downgrade is done, I busy implementing the Excubo canvas in a project and will play around with it.

The alternative is Blazor.Extensions.Canvas. I've implemented this before but it's missing stuff that seems to work in your version of canvas. Also, that codebase isn't worked on since 2021, it seems to be dead.

For me that is a big reason i'm trying Excubo right now.

Your fast response also makes a big differende btw.

**Comment by stefanloerwald** [comment]
I personally have the following SDKs installed and the state of main works fine for me:

```
> dotnet --list-sdks
3.1.426
5.0.214
6.0.101
6.0.203
6.0.311
7.0.203
```

Since the github build & deploy workflow uses 6.0.x, I recommend looking into whether 6.0.311 or later is installed on your device.

In any case, a downgrade to Excubo.Generators.Grouping v1.4.15 is not in any way problematic. There weren't any significant changes, only updated dependencies (only Microsoft.CodeAnalysis.*, which is quite tightly coupled with SDKs, sadly).

**Comment by ingmarcrone** [comment]
Ah ok, you were talking about the .net sdk's.
My sdks (dotnet --list-sdks):
7.0.103

My runtimes (dotnet --list-runtimes):
Microsoft.AspNetCore.App 6.0.14
Microsoft.AspNetCore.App 7.0.3
Microsoft.NETCore.App 6.0.14
Microsoft.NETCore.App 7.0.3
Microsoft.WindowsDesktop.App 6.0.14
Microsoft.WindowsDesktop.App 7.0.3

the example project (https://github.com/excubo-ag/Blazor.Canvas/tree/main/TestProject_Components) is just not building.
Its there that I downgraded the version.

In my projects the Excubo libraries work fine, it's only the downloaded example project that doesn't build
