### ISSUE TITLE
Question: Is this repository still maintained?

### ISSUE THREAD

**Issue by RENCENDANT** [excubo-ag/Blazor.Canvas#171]
Is this repository still maintained and new features will be added soon as the contributors decided to do so? Because this component helps me a lot on my project and I would like to know if I can contribute to it after I finish my project.

**Comment by stefanloerwald** [comment]
Hi @RENCENDANT,

There's no feature development planned on this project, but it is maintained. Feature proposals and pull requests will be reviewed, but there's no guarantee of a timely response.

Best regards,
Stefan
