### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by Jaders77** [excubo-ag/Blazor.Canvas#174]
This lib is just perfect for me, but...
When I look text in your demo (and in my implementation), the text is blurry, and the result doesn't look professional.
I found a link that explain problem/solution around what they call HiDPI: https://stackoverflow.com/questions/15661339/how-do-i-fix-blurry-text-in-my-html5-canvas
```
function createHiPPICanvas(width, height) {
    const ratio = window.devicePixelRatio;
    const canvas = document.createElement("canvas");

    canvas.width = width * ratio;
    canvas.height = height * ratio;
    canvas.style.width = width + "px";
    canvas.style.height = height + "px";
    canvas.getContext("2d").scale(ratio, ratio);

    return canvas;
}
```
Because it's not easy to access the ElementReference (something that can also be a good idea to expose to be able to extract some canvas informations like real width/height of dynamic class="flex-fill" from Bootstrap, or disabling mouseweel without a surrounding div), I didn't found a proper way to use js to set style.width/height of the canvas.
Maybe you can set these properties by default to HiDPI, or add an option for that somewhere, I think it should be a great improvement.

**Comment by stefanloerwald** [comment]
Fascinating! I didn't know about this aspect of canvases.

Are you able to execute the necessary code when you use a native html canvas element? Like this:

```
@inject Microsoft.JSInterop.IJSRuntime js;
<canvas @ref="normal_canvas" width="600px" height="300px"></canvas>

@code {
    private ElementReference normal_canvas;
    protected override async Task OnAfterRenderAsync(bool first_render)
    {
        if (first_render)
        {
            await using (var ctx2 = await js.GetContext2DAsync(normal_canvas))
            {
                await ctx2.FontAsync("48px serif");
                await ctx2.StrokeTextAsync("Excubo.Blazor.Canvas", 0, 150);
            }
        }
    }
}
```

With that ElementReference, you should be able to perform the necessary operations.

Please let me know if that works!

**Comment by stefanloerwald** [comment]
Closing this for now. If you can't get it to work with the above code, please show the code you're using and I'd be willing to look into it further.
