### ISSUE TITLE
About Canvas zoom in/out/move/view selected functions

### ISSUE THREAD

**Issue by albertliu63** [excubo-ag/Blazor.Canvas#177]
Hi All, 
 
  I just used this Canvas component to do some object detection in the back end and I found it seems no further functionality to do with image zoom in/out/move/view centered on selected...  Do we have to wrap other components to handle such manipulation after detected image push to front-end ? Sorry I am new to blazor canvas development. 

Best regards,
Albert Liu

**Comment by albertliu63** [comment]
https://github.com/excubo-ag/Blazor.Canvas/assets/20080437/c5bd5b3f-2ca0-4d9a-b9bd-2196483c3d70

Attaching the sample I am doing.

**Comment by stefanloerwald** [comment]
Hi @albertliu63,

It's unclear to me from both description and video what you're trying to achieve. Could you show code?

Thanks
Stefan

**Comment by albertliu63** [comment]
Hi Stefan, 

  I just found some wrapper  "PanZoom" to let Canvas zoomable and movable. Just I found if I clearRect for first Canvas and redraw detected image on second Canvas the detected image floated on the page like the video shows.  Here is my sample code : 

  <img id="source_img" style="display:none" src="@sourceImg" hidden="@isSrcShow" />
<div style="@canvasStyle" width="1024" height="768">
    <Panzoom WheelMode="WheelMode.ZoomWithWheel">
        <div @ref="@context.ElementReference" >
            <Canvas @ref="srcCanvas" id="opencvCanvas" width="4096" height="3072">
                Your browser does not support the HTML5 canvas tag.
            </Canvas>
        </div>
    </Panzoom>
</div>
<div style="@canvasStyle" width="1024" height="768" hidden="@isDstShow">
    <Panzoom WheelMode="WheelMode.ZoomWithWheel">
        <div @ref="@context.ElementReference" >
            <Canvas @ref="dstCanvas" width="4096" height="3072">
                Your browser does not support the HTML5 canvas tag.
            </Canvas>
        </div>
    </Panzoom>
</div>
async Task OnChanged(FileChangedEventArgs e)
{
    try
    {
        var file = e.Files.FirstOrDefault();
        if (file == null)
        {
            LoadingVisibility = Visibility.Invisible;
            return;
        }
        LoadingVisibility = Visibility.Visible;
        using (MemoryStream result = new MemoryStream())
        {
            await file.OpenReadStream(long.MaxValue).CopyToAsync(result);

            SourcePdfInputDto input = new SourcePdfInputDto
                {
                    Content = result.ToArray(),
                    Name = file.Name
                };
            SourcePdfOutputDto test = await _pdfExtractService.ConvertImageFromPDFSignleAsync(input);
            int fileExtPos = test.Name.LastIndexOf(".");

            if (fileExtPos >= 0)
            {
                fileName = test.Name;
                isSrcShow = false;
                isDstShow = true;
                imgUrl = @"images/" + test.Name.Substring(0, fileExtPos) + "/" + test.Name;

               
                tmpImageByte = await httpClient.GetByteArrayAsync(@"images/" + test.Name.Substring(0, fileExtPos) + "/" + test.Name);
              
                Console.WriteLine(tmpImageByte.Length);
                srcMat ??= Mat.FromImageData(tmpImageByte, ImreadModes.Grayscale);
                sourceImg = $"data:image/png;base64," + Convert.ToBase64String(tmpImageByte);
                await InvokeAsync(StateHasChanged);
                await jsRuntime.InvokeVoidAsync("eval", "myimage = document.getElementById('source_img')");
                using (var img = SixLabors.ImageSharp.Image.Load(tmpImageByte))
                {
                    await using (var ctx1 = await srcCanvas.GetContext2DAsync())
                    {
                        await ctx1.ClearRectAsync(0, 0, 1024, 768);
                        await ctx1.DrawImageAsync("myimage", 0, 0, img.Width, img.Height);
                    }
                }
            }
        }
    }
    catch (Exception exc)
    {
        Console.WriteLine(exc.Message);
    }
    finally
    {
        StateHasChanged();
        LoadingVisibility = Visibility.Invisible;
        canvasStyle = "border: 5px solid gray";
    }
}

private async Task DetectObjects()
 {
     try
     {
         SourcePdfNameDto input = new SourcePdfNameDto
             {
                 Name = fileName
             };
         DetectImgDto res = await _pdfExtractService.DectectImageFromPDFSignleAsync(input);

         if (res.ObjList != null && res.ObjList.Count > 0)
         {
             //draw rec and words...
             isSrcShow = true;
             isDstShow = false;
             await using (var ctx1 = await dstCanvas.GetContext2DAsync())
             {
                 using (var img = SixLabors.ImageSharp.Image.Load(tmpImageByte))
                 {
                     await ctx1.ClearRectAsync(0, 0, 4091, 3072);
                     await jsRuntime.InvokeVoidAsync("eval", "myDetectedImage = document.getElementById('source_img')");
                     await ctx1.DrawImageAsync("myDetectedImage", 0, 0, img.Width, img.Height);
                     foreach (var itm in res.ObjList)
                     {
                         System.Drawing.Rectangle value = itm.DisplayRec.Value;
                         await ctx1.FillStyleAsync("red");
                         await ctx1.FillTextAsync(itm.name + "_" + itm.confidence, value.X, value.Y);
                     }
                      
                     await InvokeAsync(StateHasChanged);
                 }

             }
         }
     }
     catch (Exception ex)
     {
         Console.WriteLine(ex.Message);
     }
     finally
     {
         StateHasChanged();
         canvasStyle = "border: 5px solid red";
     }

 }

**Comment by albertliu63** [comment]
Add a video for reference. Thanks a lot. 

https://youtu.be/JGdcLfX1j5I

**Comment by albertliu63** [comment]
Hi @stefanloerwald 

     I resolved the floating problem by removing the style change after detection.  I found diagram is useful as well to zoom/pan.  Just if we want to do some cropping for labeling the object, It seems I have to wrap another tool. Thanks. 


Best regards,
Albert Liu
