### ISSUE TITLE
Cannot draw on top of another image

### ISSUE THREAD

**Issue by hammocktester** [excubo-ag/Blazor.Canvas#178]
I hope this is feasible but I am attempting to pull in an image and then draw some basic shapes over the top of it.  I have tried refrencing a 'src' parameter in the html canvas object to no avail.  It appears this is possible in javascript but is there a way to do it through this library?

**Comment by stefanloerwald** [comment]
It's unclear from your description what you're trying. Please show some code. canvas elements do not support `src`: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage
