### ISSUE TITLE
Pixel Manipulation putImageData

### ISSUE THREAD

**Issue by stefanloerwald** [excubo-ag/Blazor.Canvas#77]

**Comment by discontinuedtv** [comment]
Is there any documentation on how to use this part of the API? The first parameter is an id parameter which is later looked up on the window object. 

What‘s the recommended way to pass the image data to the API? Thanks in advance.

**Comment by stefanloerwald** [comment]
Hi @discontinuedtv,

The ImageData object should be referenced by name. This is because the ImageData object does not live in C#, only in JS. 

In JS, create and modify the ImageData object as desired:

```js
window.myImageData = new ImageData(200, 100);
```

From Blazor, reference the object:

```cs
context.PutImageDataAsync("myImageData", dx, dy);
```

Hope that helps
Stefan

**Comment by discontinuedtv** [comment]
Thank you for the reply.
